### PR TITLE
Add Github Actions

### PR DESCRIPTION
**Pull request by Luni-4**
This PR allows to run the tests for every commit both for `push` and `pull request` events.

Thanks in advance for your review! :)

### CODE REVIEW

**Comment by rr-** [comment]
@Luni-4 thank you, do I need to do anything before or after merging to enable it, or is it going to automagically work?

(I still haven't received that e-mail from GitHub.)

**Comment by Luni-4** [comment]
> @Luni-4 thank you, do I need to do anything before or after merging to enable it, or is it going to automagically work?
> 
> (I still haven't received that e-mail from GitHub.)

The PR works, but we have to wait that the `Github Actions` are enabled unfortunately.

If you want to merge it the same, no problem on my part :)

**Comment by Luni-4** [comment]
@rr- 

Yippie! `Github Actions` are enabled!

Try to force push the repository to start them, please :)

**Comment by rr-** [comment]
Hmm doesn't look like it's working?

**Comment by Luni-4** [comment]
Try to force push the repo

**Comment by rr-** [comment]
```
rr-@lightning:~/src/priv/pyffms2$ git push -f
Everything up-to-date
```

and I just pushed the Windows branch

**Comment by Luni-4** [comment]
Have you enabled the `Actions` in `Settings`?

**Comment by rr-** [comment]
Yes

**Comment by rr-** [comment]
Screenshot at 2019-11-05 12-49-21

**Comment by Luni-4** [comment]
Add a new spurious commit and force push the repo, I guess the problem is related to the internal state of this repo.

**Comment by rr-** [comment]
```
rr-@lightning:~/src/priv/pyffms2$ git touch a
rr-@lightning:~/src/priv/pyffms2$ git add a
rr-@lightning:~/src/priv/pyffms2$ git commit test
error: pathspec 'test' did not match any file(s) known to git.
rr-@lightning:~/src/priv/pyffms2$ git commit -m test
[master 2f72898] test
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 a
rr-@lightning:~/src/priv/pyffms2$ git push -f
Counting objects: 3, done.
Delta compression using up to 12 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 254 bytes | 254.00 KiB/s, done.
Total 3 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To github.com:rr-/pyffms2.git
   f9ff7bb..2f72898  master -> master
```

still nothing?

**Comment by Luni-4** [comment]
Now it works :)

**Pull request merged**
